#font_family      Hasklug Nerd Font
#font_family     Gohu Font 11 Nerd Font
#font_family       Terminess Nerd Font
font_family       Departure Mono Nerd Font


font_size 11

cursor_trail 1
cursor_trail_decay 0.1 0.4


#    __  ___      __        
#   /  |/  /___  / /______ _
#  / /|_/ / __ \/ //_/ __ `/
# / /  / / /_/ / ,< / /_/ / 
#/_/  /_/\____/_/|_|\__,_/  
#

# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

# The basic colors
# foreground              #cdd6f4
# background              #1e1e2e
# selection_foreground    #1e1e2e
# selection_background    #f5e0dc
# 
# # Cursor colors
# cursor                  #f5e0dc
# cursor_text_color       #1e1e2e
# 
# # Scrollbar colors
# scrollbar_handle_color  #9399b2
# scrollbar_track_color   #45475a
# 
# # URL color when hovering with mouse
# url_color               #f5e0dc
# 
# # Kitty window border colors
# active_border_color     #b4befe
# inactive_border_color   #6c7086
# bell_border_color       #f9e2af
# 
# # OS Window titlebar colors
# wayland_titlebar_color system
# macos_titlebar_color system
# 
# # Tab bar colors
# active_tab_foreground   #11111b
# active_tab_background   #cba6f7
# inactive_tab_foreground #cdd6f4
# inactive_tab_background #181825
# tab_bar_background      #11111b
# 
# # Colors for marks (marked text in the terminal)
# mark1_foreground #1e1e2e
# mark1_background #b4befe
# mark2_foreground #1e1e2e
# mark2_background #cba6f7
# mark3_foreground #1e1e2e
# mark3_background #74c7ec
# 
# # The 16 terminal colors
# 
# # black
# color0 #45475a
# color8 #585b70
# 
# # red
# color1 #f38ba8
# color9 #f38ba8
# 
# # green
# color2  #a6e3a1
# color10 #a6e3a1
# 
# # yellow
# color3  #f9e2af
# color11 #f9e2af
# 
# # blue
# color4  #89b4fa
# color12 #89b4fa
# 
# # magenta
# color5  #f5c2e7
# color13 #f5c2e7
# 
# # cyan
# color6  #94e2d5
# color14 #94e2d5
# 
# # white
# color7  #bac2de
# color15 #a6adc8
# 

#    ______                 __              
#   / ____/______  ___   __/ /_  ____  _  __
#  / / __/ ___/ / / / | / / __ \/ __ \| |/_/
# / /_/ / /  / /_/ /| |/ / /_/ / /_/ />  <  
# \____/_/   \__,_/ |___/_.___/\____/_/|_|  


cursor                  #928374
cursor_text_color       background

url_color               #83a598

visual_bell_color       #8ec07c
bell_border_color       #8ec07c

active_border_color     #d3869b
inactive_border_color   #665c54

foreground              #ebdbb2
background              #282828
selection_foreground    #928374
selection_background    #ebdbb2

active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836

# black  (bg3/bg4)
color0                  #665c54
color8                  #7c6f64

# red
color1                  #cc241d
color9                  #fb4934

#: green
color2                  #98971a
color10                 #b8bb26

# yellow
color3                  #d79921
color11                 #fabd2f

# blue
color4                  #458588
color12                 #83a598

# purple
color5                  #b16286
color13                 #d3869b

# aqua
color6                  #689d6a
color14                 #8ec07c

# white (fg4/fg3)
color7                  #a89984
color15                 #bdae93
